### ISSUE TITLE
#BUILD_VERSION is not replaced

### ISSUE THREAD

**Issue by AmyKosinova** [EmbedITCZ/jbehave-support#58]
Report footer hasn't replaced variable: `Created by jbehave-support reporter (build #BUILD_VERSION)`

**Comment by AmyKosinova** [comment]
@thradec Any reason to remove? https://github.com/EmbedITCZ/jbehave-support/pull/9/files#diff-fdd01033b4a2adfdbb8c3236c255ddceL72

**Comment by thradec** [comment]
Well, it seemed unnecessary to me at that time :smile: 

But I still think that we don't need BUILD_NUMBER now. I think that the current project version should be used, which is increased with each release. And standard maven resource filtering instead of antrun plugin.

**Comment by AmyKosinova** [comment]
That is exactly what this feature was made for - teaser for users, so they can see there IS a newer version, so they can depend on current. We can discuss relevancy of term "BUILD NUMBER" even implementation, but idea behind it is valid I think.

**Comment by paveljandejsek** [comment]
And I think that based on the comment above Tomas agrees with you on that 🙂  Anyway since this was a working functionality broken by mistake - why dont we temporarily return antrun plugin as a bugfix (i.e. back to the 'as it was' state) and do an enhancement PR (with maven resource plugin and project version) later down the road when someone has the time to look into that? Just my 2 cents on the matter...
