### ISSUE TITLE
Webstep timeout

### ISSUE THREAD

**Issue by mbocek** [EmbedITCZ/jbehave-support#63]
In the chromedriver we set only timeout for `driver.manage().timeouts().implicitlyWait`.
We should also set timeouts for `pageLoadTimeout`, `setScriptTimeout`. These missing timeouts cause to fall to default timeout (observed value is 300s).

**Comment by paveljandejsek** [comment]
Do we want to do this and "complicate" the provided chromedriver even further? If the user needs this they can use their own WebDriverFactory.
Basically what I am asking is - do we want to have ChromeWebDriverFactory as a reasonable "barebones" implementation for basic testing (and not change it unless we really have to), or do we want to keep adding to it?

**Comment by thradec** [comment]
Another point of view is, that our current implementation of `web.timeout` property is buggy. Because from user perspective, I set the timeout to 10s, so wft is the 300s timeout which I can see in the logs :smile:

**Comment by paveljandejsek** [comment]
True as well, and since we cant change the property name due to backwards compatibility we could change the docs... Anyway no strong opinion from my side either way, I just wanted to open discussion about how we see the place and usage of our default WebDriverFactories (since I remember being overvoted couple months ago that we want to keep them simple :smiley:  )

**Comment by mbocek** [comment]
Proposal: use same value from property `web.timeout` for `implicitlyWait`, `pageLoadTimeout`, `setScriptTimeout`. Let's discuss if we need specific properties for each method like `web.timeout. implicitlyWait`... these properties can override the default in `web.timeout`.
